project:
  resources:
    - "Resources"
    - "style_site.scss"
    - "Hal_css.css"
    - "Hal_css_dark.css"
    - "custom_hal.js"
  type: website
  output-dir: docs
website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  title: "Alexandre Daby-Seesaram"
  image: avatar.jpg
  favicon: avatar.jpg
  description: "Alexandre Daby-Seesaram, PHD, personal webpage"
  site-url: https://alexandredabyseesaram.github.io/
  navbar:
    # pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: news.qmd
        text: News
      - href: add_resources.qmd
        text: Resources
      - href: TA.qmd
        text: Teaching
      - href: education.qmd
        text: Education
      - text: CV
        href: Resources/Documents/CV.pdf
        target: _blank
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Conference incoming** - We'll be [presenting our work](https://alexandredabyseesaram.github.io/talks.html) at the incoming [VPH2024 in Stuttgart](https://vph-conference.org/) "
  #   type: light
  #   position: below-navbar

format:
  html:
    email-obfuscation: javascript
    theme:
      light: [flatly,style_site.scss]
      dark: [darkly,style_site_dark.scss]
    # mainfont: Lato 
    css: styles.css
    toc: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>



